import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
//import LoginPage from "./login/page";
import Provider from "./provider";
import Navbar from "./navbar/page";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DELL Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
       <Provider>
        <Navbar></Navbar>
          {children}
        </Provider>
        {/* <h1> This is my Site</h1>
        <LoginPage /> */}
        {/* <Link href='/login'>LoginPage</Link> */}
        </body>
    </html>
  );
}
